import { createFileRoute, Link } from "@tanstack/react-router";
import { useState, useMemo } from "react";
import { Search, Plus, Trash2, Edit3, Eye, Calendar, Phone, Users } from "lucide-react";
import { toast } from "sonner";
import AppLayout from "@/components/AppLayout";
import { PageHeader, Card, Button, Input, Label, Select } from "@/components/ui-bits";
import { usePatients } from "@/lib/db";
import { Patient, PatientStatus, PATIENT_STATUS, PATIENT_GENDERS, PATIENT_MARITAL_STATUSES } from "@/lib/store";

export const Route = createFileRoute("/pacientes/")({
  head: () => ({ meta: [{ title: "Pacientes — Oralit" }] }),
  component: PacientesPage,
});

function formatCpf(v: string) {
  v = v.replace(/\D/g, "");
  if (v.length > 11) v = v.slice(0, 11);
  return v.replace(/(\d{3})(\d)/, "$1.$2").replace(/(\d{3})(\d)/, "$1.$2").replace(/(\d{3})(\d{1,2})$/, "$1-$2");
}

function formatPhone(v: string) {
  v = v.replace(/\D/g, "");
  if (v.length > 11) v = v.slice(0, 11);
  if (v.length > 10) return v.replace(/(\d{2})(\d{5})(\d{4})/, "($1) $2-$3");
  if (v.length > 6) return v.replace(/(\d{2})(\d{4})(\d{0,4})/, "($1) $2-$3");
  if (v.length > 2) return v.replace(/(\d{2})(\d{0,5})/, "($1) $2");
  return v;
}

function calcAge(birthDate: string | undefined): number | null {
  if (!birthDate) return null;
  const birth = new Date(birthDate);
  const today = new Date();
  let age = today.getFullYear() - birth.getFullYear();
  const m = today.getMonth() - birth.getMonth();
  if (m < 0 || (m === 0 && today.getDate() < birth.getDate())) age--;
  return age;
}

const STATUS_META: Record<PatientStatus, {
  label: string;
  dot: string;
  border: string;
  badge: string;
  selected: string;
}> = {
  inativo: {
    label: "Inativo",
    dot: "bg-slate-400",
    border: "bg-slate-400",
    badge: "border-slate-200 bg-slate-100 text-slate-700",
    selected: "border-slate-400 bg-slate-50 text-slate-900",
  },
  "em tratamento": {
    label: "Em Tratamento",
    dot: "bg-emerald-500",
    border: "bg-emerald-500",
    badge: "border-emerald-200 bg-emerald-50 text-emerald-700",
    selected: "border-emerald-400 bg-emerald-50 text-emerald-800",
  },
  "em acompanhamento": {
    label: "Em Acompanhamento",
    dot: "bg-amber-500",
    border: "bg-amber-500",
    badge: "border-amber-200 bg-amber-50 text-amber-800",
    selected: "border-amber-400 bg-amber-50 text-amber-900",
  },
  "marcar c/ parceiros": {
    label: "Marcar c/ Parceiros",
    dot: "bg-violet-500",
    border: "bg-violet-500",
    badge: "border-violet-200 bg-violet-50 text-violet-700",
    selected: "border-violet-400 bg-violet-50 text-violet-800",
  },
};

function getStatusLabel(status: PatientStatus) {
  return STATUS_META[status]?.label || status;
}

const emptyPatient = (): Patient => ({
  id: "", // uuid will be generated by DB
  fullName: "",
  status: "em tratamento",
  createdAt: new Date().toISOString(),
});

function PacientesPage() {
  const [patients, setPatients, loading, error] = usePatients();
  const [search, setSearch] = useState("");
  const [statusFilter, setStatusFilter] = useState<PatientStatus | "todos">("todos");
  
  const [editingId, setEditingId] = useState<string | null>(null);
  const [draft, setDraft] = useState<Patient | null>(null);

  const filtered = useMemo(() => {
    return patients.filter((p) => {
      const q = search.toLowerCase();
      const matchSearch =
        (p.fullName || "").toLowerCase().includes(q) || (p.referenceNote || "").toLowerCase().includes(q) ||
        (p.cpf && p.cpf.includes(q)) ||
        (p.phone && p.phone.includes(q)) ||
        (p.whatsapp && p.whatsapp.includes(q)) ||
        (p.recordNumber && p.recordNumber.toLowerCase().includes(q));
      
      const matchStatus = statusFilter === "todos" || p.status === statusFilter;
      return matchSearch && matchStatus;
    });
  }, [patients, search, statusFilter]);

  const remove = async (id: string) => {
    try {
      await setPatients((prev) => prev.filter((x) => x.id !== id));
      toast.success("Paciente excluído.");
    } catch (err) {
      toast.error("Não foi possível excluir agora.");
    }
  };

  const save = async () => {
    if (!draft || !draft.fullName.trim()) return toast.error("O nome completo é obrigatório.");
    
    if (!draft.id) {
      // New patient
      const newPatient = { ...draft, id: crypto.randomUUID() };
      await setPatients((prev) => [newPatient, ...prev]);
    } else {
      // Update patient
      await setPatients((prev) => prev.map((x) => (x.id === draft.id ? draft : x)));
    }
    setEditingId(null);
    setDraft(null);
  };

  if (loading) {
    return (
      <AppLayout>
        <div className="py-10 text-center text-muted-foreground text-sm font-medium animate-pulse">
          Carregando pacientes...
        </div>
      </AppLayout>
    );
  }

  if (error) {
    return (
      <AppLayout>
        <div className="py-16 text-center">
          <div className="h-16 w-16 bg-rose-500/10 text-rose-500 rounded-full flex items-center justify-center mx-auto mb-4">
            <Users className="h-8 w-8" />
          </div>
          <h2 className="text-xl font-display font-bold mb-2 text-rose-600">Erro ao carregar pacientes</h2>
          <p className="text-muted-foreground mb-6 max-w-md mx-auto">{error}</p>
          <Button variant="outline" onClick={() => window.location.reload()}>
            Tentar Novamente
          </Button>
        </div>
      </AppLayout>
    );
  }

  return (
    <AppLayout>
      <PageHeader
        title="Pacientes"
        subtitle="Gerencie seus pacientes e acesse as fichas clínicas."
        action={
          <Button variant="gold" onClick={() => { setEditingId("new"); setDraft(emptyPatient()); }}>
            <Plus className="h-4 w-4 mr-2" /> Novo paciente
          </Button>
        }
      />

      {editingId && draft && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/40 backdrop-blur-sm animate-in fade-in duration-200">
          <div className="bg-card w-full max-w-2xl max-h-[90vh] rounded-2xl shadow-2xl flex flex-col overflow-hidden animate-in zoom-in-95 duration-200">
            <div className="px-6 py-5 border-b border-border flex items-center justify-between bg-secondary/30">
              <h2 className="text-xl font-display font-bold text-foreground">
                {editingId === "new" ? "Novo Paciente" : "Editar Paciente"}
              </h2>
              <button
                className="text-muted-foreground hover:text-foreground transition-colors p-2"
                onClick={() => { setEditingId(null); setDraft(null); }}
              >
                ✕
              </button>
            </div>
            
            <div className="p-6 overflow-y-auto space-y-8">
              {/* Seção 1: Identificação */}
              <section>
                <h3 className="text-sm font-bold text-gold tracking-wider uppercase mb-4 flex items-center gap-2">
                  <span className="w-6 h-[1px] bg-gold/30"></span> Identificação
                </h3>
                <div className="grid sm:grid-cols-2 gap-4">
                  <div className="sm:col-span-2">
                    <Label>Nome completo *</Label>
                    <Input autoFocus value={draft.fullName} onChange={(e) => setDraft({ ...draft, fullName: e.target.value })} placeholder="Ex: Maria Joaquina Silva" />

<Label>Referência</Label>
<Input
  value={draft.referenceNote || ""}
  onChange={(e) => setDraft({ ...draft, referenceNote: e.target.value })}
  placeholder="Ex: irmão do Danilo, filha da Maria, indicação do João"
/>
                  </div>
                  <div>
                    <Label>Nº Prontuário</Label>
                    <Input value={draft.recordNumber || ""} onChange={(e) => setDraft({ ...draft, recordNumber: e.target.value })} placeholder="Ex: 001/2023" />
                  </div>
                  <div>
                    <Label>Data de nascimento</Label>
                    <Input type="date" value={draft.birthDate || ""} onChange={(e) => setDraft({ ...draft, birthDate: e.target.value })} />
                    {draft.birthDate && <p className="text-xs text-muted-foreground mt-1">Idade: {calcAge(draft.birthDate)} anos</p>}
                  </div>
                  <div>
                    <Label>Sexo</Label>
                    <Select value={draft.gender || ""} onChange={(e) => setDraft({ ...draft, gender: e.target.value })}>
                      <option value="">Selecione...</option>
                      {PATIENT_GENDERS.map(g => <option key={g} value={g}>{g}</option>)}
                    </Select>
                  </div>
                  <div>
                    <Label>Estado Civil</Label>
                    <Select value={draft.maritalStatus || ""} onChange={(e) => setDraft({ ...draft, maritalStatus: e.target.value })}>
                      <option value="">Selecione...</option>
                      {PATIENT_MARITAL_STATUSES.map(s => <option key={s} value={s}>{s}</option>)}
                    </Select>
                  </div>
                  <div className="sm:col-span-2">
                    <Label>Profissão</Label>
                    <Input value={draft.profession || ""} onChange={(e) => setDraft({ ...draft, profession: e.target.value })} placeholder="Ex: Professora" />
                  </div>
                </div>
              </section>

              {/* Seção 2: Documentos */}
              <section>
                <h3 className="text-sm font-bold text-gold tracking-wider uppercase mb-4 flex items-center gap-2">
                  <span className="w-6 h-[1px] bg-gold/30"></span> Documentos
                </h3>
                <div className="grid sm:grid-cols-2 gap-4">
                  <div>
                    <Label>CPF</Label>
                    <Input value={draft.cpf || ""} onChange={(e) => setDraft({ ...draft, cpf: formatCpf(e.target.value) })} placeholder="000.000.000-00" />
                  </div>
                  <div className="flex gap-3">
                    <div className="flex-1">
                      <Label>RG</Label>
                      <Input value={draft.rg || ""} onChange={(e) => setDraft({ ...draft, rg: e.target.value.replace(/\D/g,"") })} placeholder="Apenas números" />
                    </div>
                    <div className="w-24">
                      <Label>Órgão Exp.</Label>
                      <Input value={draft.issuingAgency || ""} onChange={(e) => setDraft({ ...draft, issuingAgency: e.target.value.toUpperCase() })} placeholder="Ex: SSP" />
                    </div>
                  </div>
                </div>
              </section>

              {/* Seção 3: Contato */}
              <section>
                <h3 className="text-sm font-bold text-gold tracking-wider uppercase mb-4 flex items-center gap-2">
                  <span className="w-6 h-[1px] bg-gold/30"></span> Contato
                </h3>
                <div className="grid sm:grid-cols-2 gap-4">
                  <div>
                    <Label>Telefone Principal</Label>
                    <Input value={draft.phone || ""} onChange={(e) => setDraft({ ...draft, phone: formatPhone(e.target.value) })} placeholder="(00) 00000-0000" />
                  </div>
                  <div>
                    <Label>WhatsApp</Label>
                    <Input value={draft.whatsapp || ""} onChange={(e) => setDraft({ ...draft, whatsapp: formatPhone(e.target.value) })} placeholder="(00) 00000-0000" />
                  </div>
                </div>
              </section>

              {/* Seção 4: Endereço */}
              <section>
                <h3 className="text-sm font-bold text-gold tracking-wider uppercase mb-4 flex items-center gap-2">
                  <span className="w-6 h-[1px] bg-gold/30"></span> Endereço
                </h3>
                <div>
                  <Label>Endereço Completo</Label>
                  <Input value={draft.address || ""} onChange={(e) => setDraft({ ...draft, address: e.target.value })} placeholder="Rua, número, complemento, bairro, cidade, CEP" />
                </div>
              </section>

              {/* Seção 5: Observações */}
              <section>
                <h3 className="text-sm font-bold text-gold tracking-wider uppercase mb-4 flex items-center gap-2">
                  <span className="w-6 h-[1px] bg-gold/30"></span> Administrativo
                </h3>
                <div className="grid sm:grid-cols-2 gap-4">
                  <div>
                    <Label>Status do Paciente *</Label>
                    <Select value={draft.status} onChange={(e) => setDraft({ ...draft, status: e.target.value as PatientStatus })}>
                      {PATIENT_STATUS.map(s => <option key={s} value={s}>{getStatusLabel(s)}</option>)}
                    </Select>
                  </div>
                  <div className="sm:col-span-2">
                    <Label>Observações Internas</Label>
                    <Input value={draft.administrativeNotes || ""} onChange={(e) => setDraft({ ...draft, administrativeNotes: e.target.value })} placeholder="Anotações para a clínica..." />
                  </div>
                </div>
              </section>

            </div>
            
            <div className="px-6 py-4 border-t border-border bg-secondary/30 flex justify-end gap-3 mt-auto">
              <Button variant="outline" onClick={() => { setEditingId(null); setDraft(null); }}>Cancelar</Button>
              <Button variant="gold" onClick={save}>Salvar paciente</Button>
            </div>
          </div>
        </div>
      )}

      <Card className="mb-6 p-5">
        <div className="space-y-4">
          <div className="grid gap-4 lg:grid-cols-[minmax(420px,1fr)_240px]">
            <div className="space-y-2">
              <div className="flex items-center gap-2 text-sm font-semibold text-gold">
                <Search className="h-4 w-4" />
                <span>Buscar paciente</span>
              </div>

              <Input
                className="h-12 w-full rounded-2xl border-gold/30 bg-white px-4 text-base shadow-sm focus-visible:ring-gold/40"
                placeholder="Buscar por nome, referência, CPF, telefone ou prontuário..."
                value={search}
                onChange={(e) => setSearch(e.target.value)}
              />
            </div>

            <div className="space-y-2">
              <div className="text-sm font-semibold text-muted-foreground">
                Filtrar status
              </div>

              <Select
                className="h-12 w-full rounded-2xl border-gold/30 bg-white shadow-sm"
                value={statusFilter}
                onChange={(e) => setStatusFilter(e.target.value as any)}
              >
                <option value="todos">Todos os status</option>
                {PATIENT_STATUS.map((s) => (
                  <option key={s} value={s}>
                    {getStatusLabel(s)}
                  </option>
                ))}
              </Select>
            </div>
          </div>

          <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
            {PATIENT_STATUS.map((status) => {
              const meta = STATUS_META[status];
              const count = patients.filter((patient) => patient.status === status).length;
              const selected = statusFilter === status;

              return (
                <button
                  key={status}
                  type="button"
                  onClick={() => setStatusFilter(status)}
                  className={`flex items-center justify-between rounded-2xl border px-4 py-3 text-left transition ${
                    selected
                      ? meta.selected
                      : "border-border bg-white text-foreground hover:border-gold/40 hover:bg-[#fcfbf8]"
                  }`}
                >
                  <span className="flex min-w-0 items-center gap-2.5">
                    <span className={`h-2.5 w-2.5 shrink-0 rounded-full ${meta.dot}`} />
                    <span className="truncate text-sm font-semibold">{meta.label}</span>
                  </span>
                  <span className="ml-3 rounded-full border border-current/10 bg-white/70 px-2 py-0.5 text-xs font-bold">
                    {count}
                  </span>
                </button>
              );
            })}
          </div>
        </div>
      </Card>

      <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
        {filtered.map((p) => {
          const age = calcAge(p.birthDate);
          return (
            <Card key={p.id} className="flex flex-col relative overflow-hidden group">
              {/* Colored left border based on status */}
              <div
                className={`absolute bottom-0 left-0 top-0 w-1 ${
                  STATUS_META[p.status]?.border || "bg-muted-foreground/30"
                }`}
              />
              
              <div className="pl-3 pb-3">
                <div className="flex justify-between items-start mb-2">
                  <div className="flex-1 pr-2">
                    <h3 className="font-display font-semibold text-lg leading-tight line-clamp-1">{p.fullName}</h3>
                    <div className="flex items-center gap-2 mt-1">
                      {p.recordNumber && <span className="text-[10px] uppercase font-bold tracking-wider text-muted-foreground bg-secondary px-1.5 py-0.5 rounded">PR: {p.recordNumber}</span>}
                      {age !== null && <span className="text-xs text-muted-foreground">{age} anos</span>}
                    </div>
                  </div>
                  <span
                    className={`shrink-0 rounded-full border px-2.5 py-1 text-[11px] font-semibold ${
                      STATUS_META[p.status]?.badge || "border-border bg-secondary text-muted-foreground"
                    }`}
                  >
                    {getStatusLabel(p.status)}
                  </span>
                </div>

                <div className="text-sm text-muted-foreground space-y-1.5 mt-4">
                  {p.cpf && <div className="flex items-center gap-2"><span className="font-mono text-xs bg-secondary/50 px-1.5 rounded">{p.cpf}</span></div>}
                  {(p.phone || p.whatsapp) && (
                    <div className="flex items-center gap-2">
                      <Phone className="h-3.5 w-3.5" />
                      <span>{p.whatsapp || p.phone}</span>
                    </div>
                  )}
                  {p.createdAt && (
                    <div className="flex items-center gap-2 text-xs opacity-70">
                      <Calendar className="h-3.5 w-3.5" />
                      <span>Cadastrado em {new Date(p.createdAt).toLocaleDateString()}</span>
                    </div>
                  )}
                </div>
              </div>

              <div className="mt-auto pt-4 border-t border-border flex items-center justify-between gap-2 pl-3">
                <Link to="/pacientes/$patientId" params={{ patientId: p.id }} className="flex-1">
                  <Button variant="outline" className="w-full text-xs h-8">
                    <Eye className="h-3.5 w-3.5 mr-2" /> Abrir ficha
                  </Button>
                </Link>
                <div className="flex items-center gap-1">
                  <button 
                    className="p-1.5 text-muted-foreground hover:text-gold transition-colors"
                    onClick={() => { setDraft({ ...p }); setEditingId(p.id); }}
                    title="Editar"
                  >
                    <Edit3 className="h-4 w-4" />
                  </button>
                  <button 
                    className="p-1.5 text-muted-foreground hover:text-rose-500 transition-colors"
                    onClick={() => remove(p.id)}
                    title="Excluir"
                  >
                    <Trash2 className="h-4 w-4" />
                  </button>
                </div>
              </div>
            </Card>
          );
        })}
      </div>

      {filtered.length === 0 && search && (
        <div className="text-center py-12 text-muted-foreground">
          Nenhum paciente encontrado para essa busca.
        </div>
      )}
      {filtered.length === 0 && !search && patients.length > 0 && (
        <div className="text-center py-12 text-muted-foreground">
          Nenhum paciente com o status selecionado.
        </div>
      )}
      {patients.length === 0 && !search && (
        <div className="text-center py-16">
          <div className="h-16 w-16 bg-gold/10 text-gold rounded-full flex items-center justify-center mx-auto mb-4">
            <Users className="h-8 w-8" />
          </div>
          <h3 className="text-lg font-display font-semibold mb-1">Nenhum paciente</h3>
          <p className="text-muted-foreground text-sm mb-4">Você ainda não tem pacientes cadastrados.</p>
          <Button variant="gold" onClick={() => { setEditingId("new"); setDraft(emptyPatient()); }}>
            Cadastrar primeiro paciente
          </Button>
        </div>
      )}
    </AppLayout>
  );
}
