import { createFileRoute, Link } from "@tanstack/react-router";
import { useState, useMemo } from "react";
import { Search, Plus, Trash2, Edit3, Eye, Calendar, Phone, Users } from "lucide-react";
import AppLayout from "@/components/AppLayout";
import { PageHeader, Card, Button, Input, Label, Select, Badge } from "@/components/ui-bits";
import { usePatients } from "@/lib/db";
import { Patient, PatientStatus, PATIENT_STATUS, PATIENT_GENDERS, PATIENT_MARITAL_STATUSES } from "@/lib/store";

export const Route = createFileRoute("/pacientes/")({
  head: () => ({ meta: [{ title: "Pacientes — Oralit" }] }),
  component: PacientesPage,
});

function formatCpf(v: string) {
  v = v.replace(/\D/g, "");
  if (v.length > 11) v = v.slice(0, 11);
  return v.replace(/(\d{3})(\d)/, "$1.$2").replace(/(\d{3})(\d)/, "$1.$2").replace(/(\d{3})(\d{1,2})$/, "$1-$2");
}

function formatPhone(v: string) {
  v = v.replace(/\D/g, "");
  if (v.length > 11) v = v.slice(0, 11);
  if (v.length > 10) return v.replace(/(\d{2})(\d{5})(\d{4})/, "($1) $2-$3");
  if (v.length > 6) return v.replace(/(\d{2})(\d{4})(\d{0,4})/, "($1) $2-$3");
  if (v.length > 2) return v.replace(/(\d{2})(\d{0,5})/, "($1) $2");
  return v;
}

function calcAge(birthDate: string | undefined): number | null {
  if (!birthDate) return null;
  const birth = new Date(birthDate);
  const today = new Date();
  let age = today.getFullYear() - birth.getFullYear();
  const m = today.getMonth() - birth.getMonth();
  if (m < 0 || (m === 0 && today.getDate() < birth.getDate())) age--;
  return age;
}

const emptyPatient = (): Patient => ({
  id: "", // uuid will be generated by DB
  fullName: "",
  status: "ativo",
  createdAt: new Date().toISOString(),
});

function PacientesPage() {
  const [patients, setPatients, loading, error] = usePatients();
  const [search, setSearch] = useState("");
  const [statusFilter, setStatusFilter] = useState<PatientStatus | "todos">("todos");
  
  const [editingId, setEditingId] = useState<string | null>(null);
  const [draft, setDraft] = useState<Patient | null>(null);

  const filtered = useMemo(() => {
    return patients.filter((p) => {
      const q = search.toLowerCase();
      const matchSearch =
        (p.fullName || "").toLowerCase().includes(q) ||
        (p.cpf && p.cpf.includes(q)) ||
        (p.phone && p.phone.includes(q)) ||
        (p.whatsapp && p.whatsapp.includes(q)) ||
        (p.recordNumber && p.recordNumber.toLowerCase().includes(q));
      
      const matchStatus = statusFilter === "todos" || p.status === statusFilter;
      return matchSearch && matchStatus;
    });
  }, [patients, search, statusFilter]);

  const remove = async (id: string) => {
    if (!confirm("Excluir este paciente definitivamente?")) return;
    await setPatients((prev) => prev.filter((x) => x.id !== id));
  };

  const save = async () => {
    if (!draft || !draft.fullName.trim()) return alert("O nome completo é obrigatório.");
    
    if (!draft.id) {
      // New patient
      const newPatient = { ...draft, id: crypto.randomUUID() };
      await setPatients((prev) => [newPatient, ...prev]);
    } else {
      // Update patient
      await setPatients((prev) => prev.map((x) => (x.id === draft.id ? draft : x)));
    }
    setEditingId(null);
    setDraft(null);
  };

  if (loading) {
    return (
      <AppLayout>
        <div className="py-10 text-center text-muted-foreground text-sm font-medium animate-pulse">
          Carregando pacientes...
        </div>
      </AppLayout>
    );
  }

  if (error) {
    return (
      <AppLayout>
        <div className="py-16 text-center">
          <div className="h-16 w-16 bg-rose-500/10 text-rose-500 rounded-full flex items-center justify-center mx-auto mb-4">
            <Users className="h-8 w-8" />
          </div>
          <h2 className="text-xl font-display font-bold mb-2 text-rose-600">Erro ao carregar pacientes</h2>
          <p className="text-muted-foreground mb-6 max-w-md mx-auto">{error}</p>
          <Button variant="outline" onClick={() => window.location.reload()}>
            Tentar Novamente
          </Button>
        </div>
      </AppLayout>
    );
  }

  return (
    <AppLayout>
      <PageHeader
        title="Pacientes"
        subtitle="Gerencie seus pacientes e acesse as fichas clínicas."
        action={
          <Button variant="gold" onClick={() => { setEditingId("new"); setDraft(emptyPatient()); }}>
            <Plus className="h-4 w-4 mr-2" /> Novo paciente
          </Button>
        }
      />

      {editingId && draft && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/40 backdrop-blur-sm animate-in fade-in duration-200">
          <div className="bg-card w-full max-w-2xl max-h-[90vh] rounded-2xl shadow-2xl flex flex-col overflow-hidden animate-in zoom-in-95 duration-200">
            <div className="px-6 py-5 border-b border-border flex items-center justify-between bg-secondary/30">
              <h2 className="text-xl font-display font-bold text-foreground">
                {editingId === "new" ? "Novo Paciente" : "Editar Paciente"}
              </h2>
              <button
                className="text-muted-foreground hover:text-foreground transition-colors p-2"
                onClick={() => { setEditingId(null); setDraft(null); }}
              >
                ✕
              </button>
            </div>
            
            <div className="p-6 overflow-y-auto space-y-8">
              {/* Seção 1: Identificação */}
              <section>
                <h3 className="text-sm font-bold text-gold tracking-wider uppercase mb-4 flex items-center gap-2">
                  <span className="w-6 h-[1px] bg-gold/30"></span> Identificação
                </h3>
                <div className="grid sm:grid-cols-2 gap-4">
                  <div className="sm:col-span-2">
                    <Label>Nome completo *</Label>
                    <Input autoFocus value={draft.fullName} onChange={(e) => setDraft({ ...draft, fullName: e.target.value })} placeholder="Ex: Maria Joaquina Silva" />
                  </div>
                  <div>
                    <Label>Nº Prontuário</Label>
                    <Input value={draft.recordNumber || ""} onChange={(e) => setDraft({ ...draft, recordNumber: e.target.value })} placeholder="Ex: 001/2023" />
                  </div>
                  <div>
                    <Label>Data de nascimento</Label>
                    <Input type="date" value={draft.birthDate || ""} onChange={(e) => setDraft({ ...draft, birthDate: e.target.value })} />
                    {draft.birthDate && <p className="text-xs text-muted-foreground mt-1">Idade: {calcAge(draft.birthDate)} anos</p>}
                  </div>
                  <div>
                    <Label>Sexo</Label>
                    <Select value={draft.gender || ""} onChange={(e) => setDraft({ ...draft, gender: e.target.value })}>
                      <option value="">Selecione...</option>
                      {PATIENT_GENDERS.map(g => <option key={g} value={g}>{g}</option>)}
                    </Select>
                  </div>
                  <div>
                    <Label>Estado Civil</Label>
                    <Select value={draft.maritalStatus || ""} onChange={(e) => setDraft({ ...draft, maritalStatus: e.target.value })}>
                      <option value="">Selecione...</option>
                      {PATIENT_MARITAL_STATUSES.map(s => <option key={s} value={s}>{s}</option>)}
                    </Select>
                  </div>
                  <div className="sm:col-span-2">
                    <Label>Profissão</Label>
                    <Input value={draft.profession || ""} onChange={(e) => setDraft({ ...draft, profession: e.target.value })} placeholder="Ex: Professora" />
                  </div>
                </div>
              </section>

              {/* Seção 2: Documentos */}
              <section>
                <h3 className="text-sm font-bold text-gold tracking-wider uppercase mb-4 flex items-center gap-2">
                  <span className="w-6 h-[1px] bg-gold/30"></span> Documentos
                </h3>
                <div className="grid sm:grid-cols-2 gap-4">
                  <div>
                    <Label>CPF</Label>
                    <Input value={draft.cpf || ""} onChange={(e) => setDraft({ ...draft, cpf: formatCpf(e.target.value) })} placeholder="000.000.000-00" />
                  </div>
                  <div className="flex gap-3">
                    <div className="flex-1">
                      <Label>RG</Label>
                      <Input value={draft.rg || ""} onChange={(e) => setDraft({ ...draft, rg: e.target.value.replace(/\D/g,"") })} placeholder="Apenas números" />
                    </div>
                    <div className="w-24">
                      <Label>Órgão Exp.</Label>
                      <Input value={draft.issuingAgency || ""} onChange={(e) => setDraft({ ...draft, issuingAgency: e.target.value.toUpperCase() })} placeholder="Ex: SSP" />
                    </div>
                  </div>
                </div>
              </section>

              {/* Seção 3: Contato */}
              <section>
                <h3 className="text-sm font-bold text-gold tracking-wider uppercase mb-4 flex items-center gap-2">
                  <span className="w-6 h-[1px] bg-gold/30"></span> Contato
                </h3>
                <div className="grid sm:grid-cols-2 gap-4">
                  <div>
                    <Label>Telefone Principal</Label>
                    <Input value={draft.phone || ""} onChange={(e) => setDraft({ ...draft, phone: formatPhone(e.target.value) })} placeholder="(00) 00000-0000" />
                  </div>
                  <div>
                    <Label>WhatsApp</Label>
                    <Input value={draft.whatsapp || ""} onChange={(e) => setDraft({ ...draft, whatsapp: formatPhone(e.target.value) })} placeholder="(00) 00000-0000" />
                  </div>
                </div>
              </section>

              {/* Seção 4: Endereço */}
              <section>
                <h3 className="text-sm font-bold text-gold tracking-wider uppercase mb-4 flex items-center gap-2">
                  <span className="w-6 h-[1px] bg-gold/30"></span> Endereço
                </h3>
                <div>
                  <Label>Endereço Completo</Label>
                  <Input value={draft.address || ""} onChange={(e) => setDraft({ ...draft, address: e.target.value })} placeholder="Rua, número, complemento, bairro, cidade, CEP" />
                </div>
              </section>

              {/* Seção 5: Observações */}
              <section>
                <h3 className="text-sm font-bold text-gold tracking-wider uppercase mb-4 flex items-center gap-2">
                  <span className="w-6 h-[1px] bg-gold/30"></span> Administrativo
                </h3>
                <div className="grid sm:grid-cols-2 gap-4">
                  <div>
                    <Label>Status do Paciente *</Label>
                    <Select value={draft.status} onChange={(e) => setDraft({ ...draft, status: e.target.value as PatientStatus })}>
                      {PATIENT_STATUS.map(s => <option key={s} value={s}>{s.charAt(0).toUpperCase() + s.slice(1)}</option>)}
                    </Select>
                  </div>
                  <div className="sm:col-span-2">
                    <Label>Observações Internas</Label>
                    <Input value={draft.administrativeNotes || ""} onChange={(e) => setDraft({ ...draft, administrativeNotes: e.target.value })} placeholder="Anotações para a clínica..." />
                  </div>
                </div>
              </section>

            </div>
            
            <div className="px-6 py-4 border-t border-border bg-secondary/30 flex justify-end gap-3 mt-auto">
              <Button variant="outline" onClick={() => { setEditingId(null); setDraft(null); }}>Cancelar</Button>
              <Button variant="gold" onClick={save}>Salvar paciente</Button>
            </div>
          </div>
        </div>
      )}

      <Card className="mb-6 p-4">
        <div className="flex flex-col sm:flex-row gap-4">
          <div className="relative flex-1">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
            <Input
              className="pl-9"
              placeholder="Buscar por nome, CPF, telefone ou prontuário..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
            />
          </div>
          <Select 
            className="w-full sm:w-48"
            value={statusFilter} 
            onChange={(e) => setStatusFilter(e.target.value as any)}
          >
            <option value="todos">Todos os status</option>
            {PATIENT_STATUS.map(s => <option key={s} value={s}>{s.charAt(0).toUpperCase() + s.slice(1)}</option>)}
          </Select>
        </div>
      </Card>

      <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
        {filtered.map((p) => {
          const age = calcAge(p.birthDate);
          return (
            <Card key={p.id} className="flex flex-col relative overflow-hidden group">
              {/* Colored left border based on status */}
              <div className={`absolute left-0 top-0 bottom-0 w-1 ${
                p.status === "ativo" || p.status === "em tratamento" ? "bg-emerald-500" :
                p.status === "retorno" ? "bg-amber-500" :
                "bg-muted-foreground/30"
              }`} />
              
              <div className="pl-3 pb-3">
                <div className="flex justify-between items-start mb-2">
                  <div className="flex-1 pr-2">
                    <h3 className="font-display font-semibold text-lg leading-tight line-clamp-1">{p.fullName}</h3>
                    <div className="flex items-center gap-2 mt-1">
                      {p.recordNumber && <span className="text-[10px] uppercase font-bold tracking-wider text-muted-foreground bg-secondary px-1.5 py-0.5 rounded">PR: {p.recordNumber}</span>}
                      {age !== null && <span className="text-xs text-muted-foreground">{age} anos</span>}
                    </div>
                  </div>
                  <Badge variant={
                    p.status === "ativo" || p.status === "em tratamento" ? "success" : 
                    p.status === "retorno" ? "warning" : "secondary"
                  } className="capitalize shrink-0">
                    {p.status}
                  </Badge>
                </div>

                <div className="text-sm text-muted-foreground space-y-1.5 mt-4">
                  {p.cpf && <div className="flex items-center gap-2"><span className="font-mono text-xs bg-secondary/50 px-1.5 rounded">{p.cpf}</span></div>}
                  {(p.phone || p.whatsapp) && (
                    <div className="flex items-center gap-2">
                      <Phone className="h-3.5 w-3.5" />
                      <span>{p.whatsapp || p.phone}</span>
                    </div>
                  )}
                  {p.createdAt && (
                    <div className="flex items-center gap-2 text-xs opacity-70">
                      <Calendar className="h-3.5 w-3.5" />
                      <span>Cadastrado em {new Date(p.createdAt).toLocaleDateString()}</span>
                    </div>
                  )}
                </div>
              </div>

              <div className="mt-auto pt-4 border-t border-border flex items-center justify-between gap-2 pl-3">
                <Link to="/pacientes/$patientId" params={{ patientId: p.id }} className="flex-1">
                  <Button variant="outline" className="w-full text-xs h-8">
                    <Eye className="h-3.5 w-3.5 mr-2" /> Abrir ficha
                  </Button>
                </Link>
                <div className="flex items-center gap-1">
                  <button 
                    className="p-1.5 text-muted-foreground hover:text-gold transition-colors"
                    onClick={() => { setDraft({ ...p }); setEditingId(p.id); }}
                    title="Editar"
                  >
                    <Edit3 className="h-4 w-4" />
                  </button>
                  <button 
                    className="p-1.5 text-muted-foreground hover:text-rose-500 transition-colors"
                    onClick={() => remove(p.id)}
                    title="Excluir"
                  >
                    <Trash2 className="h-4 w-4" />
                  </button>
                </div>
              </div>
            </Card>
          );
        })}
      </div>

      {filtered.length === 0 && search && (
        <div className="text-center py-12 text-muted-foreground">
          Nenhum paciente encontrado para essa busca.
        </div>
      )}
      {filtered.length === 0 && !search && patients.length > 0 && (
        <div className="text-center py-12 text-muted-foreground">
          Nenhum paciente com o status selecionado.
        </div>
      )}
      {patients.length === 0 && !search && (
        <div className="text-center py-16">
          <div className="h-16 w-16 bg-gold/10 text-gold rounded-full flex items-center justify-center mx-auto mb-4">
            <Users className="h-8 w-8" />
          </div>
          <h3 className="text-lg font-display font-semibold mb-1">Nenhum paciente</h3>
          <p className="text-muted-foreground text-sm mb-4">Você ainda não tem pacientes cadastrados.</p>
          <Button variant="gold" onClick={() => { setEditingId("new"); setDraft(emptyPatient()); }}>
            Cadastrar primeiro paciente
          </Button>
        </div>
      )}
    </AppLayout>
  );
}
