/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as ProcedimentosRouteImport } from './routes/procedimentos'
import { Route as PrecificarRouteImport } from './routes/precificar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InsumosRouteImport } from './routes/insumos'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as CustosFixosRouteImport } from './routes/custos-fixos'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PacientesIndexRouteImport } from './routes/pacientes.index'
import { Route as PacientesPatientIdRouteImport } from './routes/pacientes_.$patientId'

const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcedimentosRoute = ProcedimentosRouteImport.update({
  id: '/procedimentos',
  path: '/procedimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecificarRoute = PrecificarRouteImport.update({
  id: '/precificar',
  path: '/precificar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InsumosRoute = InsumosRouteImport.update({
  id: '/insumos',
  path: '/insumos',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const CustosFixosRoute = CustosFixosRouteImport.update({
  id: '/custos-fixos',
  path: '/custos-fixos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesIndexRoute = PacientesIndexRouteImport.update({
  id: '/pacientes/',
  path: '/pacientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesPatientIdRoute = PacientesPatientIdRouteImport.update({
  id: '/pacientes_/$patientId',
  path: '/pacientes/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/cadastro': typeof CadastroRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/custos-fixos': typeof CustosFixosRoute
  '/historico': typeof HistoricoRoute
  '/insumos': typeof InsumosRoute
  '/login': typeof LoginRoute
  '/precificar': typeof PrecificarRoute
  '/procedimentos': typeof ProcedimentosRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/relatorios': typeof RelatoriosRoute
  '/pacientes/$patientId': typeof PacientesPatientIdRoute
  '/pacientes/': typeof PacientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/cadastro': typeof CadastroRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/custos-fixos': typeof CustosFixosRoute
  '/historico': typeof HistoricoRoute
  '/insumos': typeof InsumosRoute
  '/login': typeof LoginRoute
  '/precificar': typeof PrecificarRoute
  '/procedimentos': typeof ProcedimentosRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/relatorios': typeof RelatoriosRoute
  '/pacientes/$patientId': typeof PacientesPatientIdRoute
  '/pacientes': typeof PacientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/cadastro': typeof CadastroRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/custos-fixos': typeof CustosFixosRoute
  '/historico': typeof HistoricoRoute
  '/insumos': typeof InsumosRoute
  '/login': typeof LoginRoute
  '/precificar': typeof PrecificarRoute
  '/procedimentos': typeof ProcedimentosRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/relatorios': typeof RelatoriosRoute
  '/pacientes_/$patientId': typeof PacientesPatientIdRoute
  '/pacientes/': typeof PacientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/cadastro'
    | '/configuracoes'
    | '/custos-fixos'
    | '/historico'
    | '/insumos'
    | '/login'
    | '/precificar'
    | '/procedimentos'
    | '/recuperar-senha'
    | '/relatorios'
    | '/pacientes/$patientId'
    | '/pacientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/cadastro'
    | '/configuracoes'
    | '/custos-fixos'
    | '/historico'
    | '/insumos'
    | '/login'
    | '/precificar'
    | '/procedimentos'
    | '/recuperar-senha'
    | '/relatorios'
    | '/pacientes/$patientId'
    | '/pacientes'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/cadastro'
    | '/configuracoes'
    | '/custos-fixos'
    | '/historico'
    | '/insumos'
    | '/login'
    | '/precificar'
    | '/procedimentos'
    | '/recuperar-senha'
    | '/relatorios'
    | '/pacientes_/$patientId'
    | '/pacientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  CadastroRoute: typeof CadastroRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  CustosFixosRoute: typeof CustosFixosRoute
  HistoricoRoute: typeof HistoricoRoute
  InsumosRoute: typeof InsumosRoute
  LoginRoute: typeof LoginRoute
  PrecificarRoute: typeof PrecificarRoute
  ProcedimentosRoute: typeof ProcedimentosRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RelatoriosRoute: typeof RelatoriosRoute
  PacientesPatientIdRoute: typeof PacientesPatientIdRoute
  PacientesIndexRoute: typeof PacientesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procedimentos': {
      id: '/procedimentos'
      path: '/procedimentos'
      fullPath: '/procedimentos'
      preLoaderRoute: typeof ProcedimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precificar': {
      id: '/precificar'
      path: '/precificar'
      fullPath: '/precificar'
      preLoaderRoute: typeof PrecificarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insumos': {
      id: '/insumos'
      path: '/insumos'
      fullPath: '/insumos'
      preLoaderRoute: typeof InsumosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custos-fixos': {
      id: '/custos-fixos'
      path: '/custos-fixos'
      fullPath: '/custos-fixos'
      preLoaderRoute: typeof CustosFixosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes/': {
      id: '/pacientes/'
      path: '/pacientes'
      fullPath: '/pacientes/'
      preLoaderRoute: typeof PacientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes_/$patientId': {
      id: '/pacientes_/$patientId'
      path: '/pacientes/$patientId'
      fullPath: '/pacientes/$patientId'
      preLoaderRoute: typeof PacientesPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  CadastroRoute: CadastroRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  CustosFixosRoute: CustosFixosRoute,
  HistoricoRoute: HistoricoRoute,
  InsumosRoute: InsumosRoute,
  LoginRoute: LoginRoute,
  PrecificarRoute: PrecificarRoute,
  ProcedimentosRoute: ProcedimentosRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RelatoriosRoute: RelatoriosRoute,
  PacientesPatientIdRoute: PacientesPatientIdRoute,
  PacientesIndexRoute: PacientesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
