/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as ProcedimentosRouteImport } from './routes/procedimentos'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrecificarRouteImport } from './routes/precificar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InsumosRouteImport } from './routes/insumos'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as DataDeletionRouteImport } from './routes/data-deletion'
import { Route as CustosFixosRouteImport } from './routes/custos-fixos'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CentralIaRouteImport } from './routes/central-ia'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as ArmazenamentoRouteImport } from './routes/armazenamento'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PacientesIndexRouteImport } from './routes/pacientes.index'
import { Route as PacientesPatientIdRouteImport } from './routes/pacientes_.$patientId'
import { Route as ApiWhatsappWebhookRouteImport } from './routes/api/whatsapp/webhook'

const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcedimentosRoute = ProcedimentosRouteImport.update({
  id: '/procedimentos',
  path: '/procedimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecificarRoute = PrecificarRouteImport.update({
  id: '/precificar',
  path: '/precificar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InsumosRoute = InsumosRouteImport.update({
  id: '/insumos',
  path: '/insumos',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const DataDeletionRoute = DataDeletionRouteImport.update({
  id: '/data-deletion',
  path: '/data-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const CustosFixosRoute = CustosFixosRouteImport.update({
  id: '/custos-fixos',
  path: '/custos-fixos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralIaRoute = CentralIaRouteImport.update({
  id: '/central-ia',
  path: '/central-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const ArmazenamentoRoute = ArmazenamentoRouteImport.update({
  id: '/armazenamento',
  path: '/armazenamento',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesIndexRoute = PacientesIndexRouteImport.update({
  id: '/pacientes/',
  path: '/pacientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesPatientIdRoute = PacientesPatientIdRouteImport.update({
  id: '/pacientes_/$patientId',
  path: '/pacientes/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappWebhookRoute = ApiWhatsappWebhookRouteImport.update({
  id: '/api/whatsapp/webhook',
  path: '/api/whatsapp/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/armazenamento': typeof ArmazenamentoRoute
  '/cadastro': typeof CadastroRoute
  '/central-ia': typeof CentralIaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/custos-fixos': typeof CustosFixosRoute
  '/data-deletion': typeof DataDeletionRoute
  '/historico': typeof HistoricoRoute
  '/insumos': typeof InsumosRoute
  '/login': typeof LoginRoute
  '/precificar': typeof PrecificarRoute
  '/privacy': typeof PrivacyRoute
  '/procedimentos': typeof ProcedimentosRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/relatorios': typeof RelatoriosRoute
  '/terms': typeof TermsRoute
  '/whatsapp': typeof WhatsappRoute
  '/pacientes/$patientId': typeof PacientesPatientIdRoute
  '/pacientes/': typeof PacientesIndexRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/armazenamento': typeof ArmazenamentoRoute
  '/cadastro': typeof CadastroRoute
  '/central-ia': typeof CentralIaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/custos-fixos': typeof CustosFixosRoute
  '/data-deletion': typeof DataDeletionRoute
  '/historico': typeof HistoricoRoute
  '/insumos': typeof InsumosRoute
  '/login': typeof LoginRoute
  '/precificar': typeof PrecificarRoute
  '/privacy': typeof PrivacyRoute
  '/procedimentos': typeof ProcedimentosRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/relatorios': typeof RelatoriosRoute
  '/terms': typeof TermsRoute
  '/whatsapp': typeof WhatsappRoute
  '/pacientes/$patientId': typeof PacientesPatientIdRoute
  '/pacientes': typeof PacientesIndexRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/armazenamento': typeof ArmazenamentoRoute
  '/cadastro': typeof CadastroRoute
  '/central-ia': typeof CentralIaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/custos-fixos': typeof CustosFixosRoute
  '/data-deletion': typeof DataDeletionRoute
  '/historico': typeof HistoricoRoute
  '/insumos': typeof InsumosRoute
  '/login': typeof LoginRoute
  '/precificar': typeof PrecificarRoute
  '/privacy': typeof PrivacyRoute
  '/procedimentos': typeof ProcedimentosRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/relatorios': typeof RelatoriosRoute
  '/terms': typeof TermsRoute
  '/whatsapp': typeof WhatsappRoute
  '/pacientes_/$patientId': typeof PacientesPatientIdRoute
  '/pacientes/': typeof PacientesIndexRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/armazenamento'
    | '/cadastro'
    | '/central-ia'
    | '/configuracoes'
    | '/custos-fixos'
    | '/data-deletion'
    | '/historico'
    | '/insumos'
    | '/login'
    | '/precificar'
    | '/privacy'
    | '/procedimentos'
    | '/recuperar-senha'
    | '/relatorios'
    | '/terms'
    | '/whatsapp'
    | '/pacientes/$patientId'
    | '/pacientes/'
    | '/api/whatsapp/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/armazenamento'
    | '/cadastro'
    | '/central-ia'
    | '/configuracoes'
    | '/custos-fixos'
    | '/data-deletion'
    | '/historico'
    | '/insumos'
    | '/login'
    | '/precificar'
    | '/privacy'
    | '/procedimentos'
    | '/recuperar-senha'
    | '/relatorios'
    | '/terms'
    | '/whatsapp'
    | '/pacientes/$patientId'
    | '/pacientes'
    | '/api/whatsapp/webhook'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/armazenamento'
    | '/cadastro'
    | '/central-ia'
    | '/configuracoes'
    | '/custos-fixos'
    | '/data-deletion'
    | '/historico'
    | '/insumos'
    | '/login'
    | '/precificar'
    | '/privacy'
    | '/procedimentos'
    | '/recuperar-senha'
    | '/relatorios'
    | '/terms'
    | '/whatsapp'
    | '/pacientes_/$patientId'
    | '/pacientes/'
    | '/api/whatsapp/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  ArmazenamentoRoute: typeof ArmazenamentoRoute
  CadastroRoute: typeof CadastroRoute
  CentralIaRoute: typeof CentralIaRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  CustosFixosRoute: typeof CustosFixosRoute
  DataDeletionRoute: typeof DataDeletionRoute
  HistoricoRoute: typeof HistoricoRoute
  InsumosRoute: typeof InsumosRoute
  LoginRoute: typeof LoginRoute
  PrecificarRoute: typeof PrecificarRoute
  PrivacyRoute: typeof PrivacyRoute
  ProcedimentosRoute: typeof ProcedimentosRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RelatoriosRoute: typeof RelatoriosRoute
  TermsRoute: typeof TermsRoute
  WhatsappRoute: typeof WhatsappRoute
  PacientesPatientIdRoute: typeof PacientesPatientIdRoute
  PacientesIndexRoute: typeof PacientesIndexRoute
  ApiWhatsappWebhookRoute: typeof ApiWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procedimentos': {
      id: '/procedimentos'
      path: '/procedimentos'
      fullPath: '/procedimentos'
      preLoaderRoute: typeof ProcedimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precificar': {
      id: '/precificar'
      path: '/precificar'
      fullPath: '/precificar'
      preLoaderRoute: typeof PrecificarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insumos': {
      id: '/insumos'
      path: '/insumos'
      fullPath: '/insumos'
      preLoaderRoute: typeof InsumosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-deletion': {
      id: '/data-deletion'
      path: '/data-deletion'
      fullPath: '/data-deletion'
      preLoaderRoute: typeof DataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custos-fixos': {
      id: '/custos-fixos'
      path: '/custos-fixos'
      fullPath: '/custos-fixos'
      preLoaderRoute: typeof CustosFixosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/central-ia': {
      id: '/central-ia'
      path: '/central-ia'
      fullPath: '/central-ia'
      preLoaderRoute: typeof CentralIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/armazenamento': {
      id: '/armazenamento'
      path: '/armazenamento'
      fullPath: '/armazenamento'
      preLoaderRoute: typeof ArmazenamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes/': {
      id: '/pacientes/'
      path: '/pacientes'
      fullPath: '/pacientes/'
      preLoaderRoute: typeof PacientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes_/$patientId': {
      id: '/pacientes_/$patientId'
      path: '/pacientes/$patientId'
      fullPath: '/pacientes/$patientId'
      preLoaderRoute: typeof PacientesPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp/webhook': {
      id: '/api/whatsapp/webhook'
      path: '/api/whatsapp/webhook'
      fullPath: '/api/whatsapp/webhook'
      preLoaderRoute: typeof ApiWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  ArmazenamentoRoute: ArmazenamentoRoute,
  CadastroRoute: CadastroRoute,
  CentralIaRoute: CentralIaRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  CustosFixosRoute: CustosFixosRoute,
  DataDeletionRoute: DataDeletionRoute,
  HistoricoRoute: HistoricoRoute,
  InsumosRoute: InsumosRoute,
  LoginRoute: LoginRoute,
  PrecificarRoute: PrecificarRoute,
  PrivacyRoute: PrivacyRoute,
  ProcedimentosRoute: ProcedimentosRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RelatoriosRoute: RelatoriosRoute,
  TermsRoute: TermsRoute,
  WhatsappRoute: WhatsappRoute,
  PacientesPatientIdRoute: PacientesPatientIdRoute,
  PacientesIndexRoute: PacientesIndexRoute,
  ApiWhatsappWebhookRoute: ApiWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
